lily = User.create!(username: 'lily', password: 'password', name: 'Lily')
tim = User.create!(username: 'tim', password: 'password', name: 'Tim')
kelly = User.create!(username: 'kelly', password: 'password', name: 'Kelly')
amy = User.create!(username: 'amy', password: 'password', name: 'Amy')
littletimmy = User.create!(username: 'littletimmy', password: 'password', name: 'Little Timmy')
cow = User.create!(username: 'cow', password: 'password', name: 'Cow')
corgi = User.create!(username: 'corgi', password: 'password', name: 'Corgi')

kwan_family = Group.create!(title: 'kwan family', description: 'the coolest')
koh_household = Group.create!(title: 'koh household', description: 'the hottest')
pet_world = Group.create!(title: 'pet world', description: 'the cutest')

GroupMembership.create!(member_user_id: 1, group_id: 1, is_admin: true)
GroupMembership.create!(member_user_id: 3, group_id: 1, is_admin: false)
GroupMembership.create!(member_user_id: 4, group_id: 1, is_admin: false)

GroupMembership.create!(member_user_id: 1, group_id: 2, is_admin: false)
GroupMembership.create!(member_user_id: 2, group_id: 2, is_admin: true)
GroupMembership.create!(member_user_id: 5, group_id: 2, is_admin: false)
GroupMembership.create!(member_user_id: 6, group_id: 2, is_admin: true)

GroupMembership.create!(member_user_id: 6, group_id: 3, is_admin: false)
GroupMembership.create!(member_user_id: 7, group_id: 3, is_admin: true)

Event.create!(title: 'dinner', description: 'yummy food', group_id: 1, host_user_id: 1)
Event.create!(title: 'lunch', description: 'yummy food again', group_id: 2, host_user_id: 2)
Event.create!(title: 'bowling', description: 'fun times', group_id: 2, host_user_id: 5)
Event.create!(title: 'play with dogs', description: 'corgi day', group_id: 1, host_user_id: 3)
Event.create!(title: 'girls night out', description: 'yaas turnt', group_id: 1, host_user_id: 1)
Event.create!(title: 'destroy human things', description: 'evil af pets', group_id: 3, host_user_id: 6)

EventResponse.create!(event_id: 1, respondee_user_id: 1, response: 'definitely_going')
EventResponse.create!(event_id: 2, respondee_user_id: 2, response: 'definitely_going')
EventResponse.create!(event_id: 3, respondee_user_id: 5, response: 'definitely_going')
EventResponse.create!(event_id: 4, respondee_user_id: 3, response: 'definitely_going')
EventResponse.create!(event_id: 5, respondee_user_id: 1, response: 'definitely_going')
EventResponse.create!(event_id: 6, respondee_user_id: 6, response: 'definitely_going')
